[package] 
name = "elysium-client" 
version = "0.1.0" 
edition = "2021" 
 
[dependencies]
rtnetlink = "0.14.1"
tokio = { version = "1.42.0", features = ["full"] }
futures-util = "0.3.31"


[profile.release]
strip = "symbols"
panic = "abort"
codegen-units = 1