version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/client"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/containers"
    schedule:
      interval: "daily"
