version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "live"

  - package-ecosystem: "cargo"
    directory: "/client"
    schedule:
      interval: "live"
