version: '3'
services:
  postgres:
    image: postgres:latest
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - ../.env
    ports:
      - "8002:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
