version: '3'
services:
  postgres:
    image: postgres:latest
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - ../.env
    ports:
      - "8002:80"
    depends_on:
      - postgres

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "8001:5540"
    depends_on:
      - redis

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
